export enum ActionsUser {
  USER_LOGIN = 'USER_LOGIN',
  USER_ID = 'USER_ID',
  USER_PROFILE = 'USER_PROFILE',
  USER_RESUME = 'USER_RESUME',
  USER_REQUESTS = 'USER_REQUESTS',
  USER_QUESTIONS = 'USER_QUESTIONS',
  USER_NOTIFICATIONS = 'USER_NOTIFICATIONS',
  USER_REPORTS = 'USER_REPORTS',
}

export enum ActionsService {
  SHOW_POPUP = 'SHOW_POPUP',
  CONTROL_METHODS = 'CONTROL_METHODS',
  CONTROL_OBJECTS = 'CONTROL_OBJECTS',
  USER_QUALIFICATION = 'USER_QUALIFICATION',
  OFFLINE_MODE = 'OFFLINE_MODE',
  SHOW_LICENSE_REQUIRED = 'SHOW_LICENSE_REQUIRED',
  OPEN_NOTIFICATION_LIST = 'OPEN_NOTIFICATION_LIST',
}

export enum ActionsQuery {
  USER_QUESTIONS_QUERY = 'USER_QUESTIONS_QUERY',
  USER_REPORTS_QUERY = 'USER_REPORTS_QUERY',
  USER_REQUESTS_QUERY = 'USER_REQUESTS_QUERY',
}
