import { Job } from '../../types/job';

export const fakeJobs: Job[] = [
  {
    id: '1',
    openDate: new Date(2021, 5, 26, 12, 0, 0, 0),
    header:
      'Заголовок запроса 1 Заголовок запроса 1 Заголовок запроса 1 Заголовок запроса 1 Заголовок запроса 1',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 1',
    qualification: '1-я',
    startDate: new Date(2021, 11, 17, 12, 0, 0, 0),
    endDate: new Date(2021, 11, 18, 18, 0, 0, 0),
    cost: 30000,
    wasRespond: false,
    canRespond: false,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '2',
    openDate: new Date(2021, 5, 26, 18, 0, 0, 0),
    header: 'Заголовок запроса 2',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 2',
    qualification: '1-я',
    startDate: new Date(2021, 5, 17, 12, 0, 0, 0),
    endDate: new Date(2021, 5, 18, 18, 0, 0, 0),
    cost: 80000,
    wasRespond: false,
    canRespond: false,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '3',
    openDate: new Date(2021, 8, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 3',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 3',
    qualification: '1-я',
    startDate: new Date(2021, 5, 2, 12, 0, 0, 0),
    endDate: new Date(2021, 5, 3, 15, 0, 0, 0),
    cost: 700,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '4',
    openDate: new Date(2021, 6, 10, 12, 0, 0, 0),
    header: 'Заголовок запроса 4',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 4',
    qualification: '1-я',
    startDate: new Date(2021, 5, 2, 12, 0, 0, 0),
    endDate: new Date(2021, 5, 3, 15, 0, 0, 0),
    cost: 4567,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '5',
    openDate: new Date(2021, 7, 10, 12, 0, 0, 0),
    header: 'Заголовок запроса 5',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 5',
    qualification: '1-я',
    startDate: new Date(),
    endDate: new Date(),
    cost: 30000,
    wasRespond: true,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '6',
    openDate: new Date(2021, 7, 15, 12, 0, 0, 0),
    header: 'Заголовок запроса 6',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 6',
    qualification: '1-я',
    startDate: new Date(2021, 8, 2, 12, 0, 0, 0),
    endDate: new Date(2021, 9, 3, 15, 0, 0, 0),
    cost: 36554,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '7',
    openDate: new Date(2021, 7, 20, 12, 0, 0, 0),
    header: 'Заголовок запроса 7',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 7',
    qualification: '1-я',
    startDate: new Date(2021, 8, 2, 12, 0, 0, 0),
    endDate: new Date(2021, 9, 3, 15, 0, 0, 0),
    cost: 44498,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '8',
    openDate: new Date(),
    header: 'Заголовок запроса 8',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 8',
    qualification: '1-я',
    startDate: new Date(),
    endDate: new Date(),
    cost: 30000,
    wasRespond: true,
    canRespond: false,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '9',
    openDate: new Date(2021, 7, 24, 12, 0, 0, 0),
    header: 'Заголовок запроса 9',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 9',
    qualification: '1-я',
    startDate: new Date(2021, 8, 24, 12, 0, 0, 0),
    endDate: new Date(2021, 9, 27, 15, 0, 0, 0),
    cost: 78898,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '10',
    openDate: new Date(2021, 7, 14, 12, 0, 0, 0),
    header: 'Заголовок запроса 10',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 10',
    qualification: '1-я',
    startDate: new Date(2021, 8, 24, 14, 0, 0, 0),
    endDate: new Date(2021, 9, 27, 18, 0, 0, 0),
    cost: 36541,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '11',
    openDate: new Date(2021, 7, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 11',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 11',
    qualification: '1-я',
    startDate: new Date(2021, 10, 24, 14, 0, 0, 0),
    endDate: new Date(2021, 11, 27, 18, 0, 0, 0),
    cost: 89564,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '12',
    openDate: new Date(2021, 4, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 12',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 12',
    qualification: '1-я',
    startDate: new Date(2021, 10, 24, 10, 0, 0, 0),
    endDate: new Date(2021, 11, 27, 15, 0, 0, 0),
    cost: 74236,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '13',
    openDate: new Date(2021, 2, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 13',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 13',
    qualification: '1-я',
    startDate: new Date(2021, 8, 24, 10, 0, 0, 0),
    endDate: new Date(2021, 9, 27, 15, 0, 0, 0),
    cost: 478,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '14',
    openDate: new Date(2021, 4, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 14',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 14',
    qualification: '1-я',
    startDate: new Date(2021, 8, 2, 10, 0, 0, 0),
    endDate: new Date(2021, 9, 10, 15, 0, 0, 0),
    cost: 3298,
    wasRespond: false,
    canRespond: false,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '15',
    openDate: new Date(2021, 7, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 15',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 15',
    qualification: '1-я',
    startDate: new Date(2021, 8, 5, 10, 0, 0, 0),
    endDate: new Date(2021, 9, 10, 15, 0, 0, 0),
    cost: 3298,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
  {
    id: '16',
    openDate: new Date(2021, 1, 26, 12, 0, 0, 0),
    header: 'Заголовок запроса 16',
    method: 'МК',
    target: 'Оборудование нефтяной и газовой промышленности 16',
    qualification: '1-я',
    startDate: new Date(2021, 8, 5, 14, 0, 0, 0),
    endDate: new Date(2021, 9, 10, 15, 0, 0, 0),
    cost: 44894,
    wasRespond: false,
    canRespond: true,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil, aut repellendus. Voluptas fuga praesentium illum at asperiores! Minima ut quo corporis qui tempora laudantium, dignissimos, voluptatem sint eaque officia accusantium.',
  },
];
